### ISSUE TITLE
proxyv2 cannot collector istio_* metrics

### ISSUE THREAD

**Issue by Mengkzhaoyun** [querycap/istio#2]
the proxyv2 image cannot collect the istio_* metrics
such as
istio_requests_total

is there any bugs through the envoy build?

**Comment by morlay** [comment]
@Mengkzhaoyun

seems some configuration issue, i will check it.

in arm64 pod, the connection_security_policy is `unknown` but amd64 is `mutual_tls`
```
istio_requests_total{connection_security_policy="unknown", destination_app="srv-octohelm", destination_canonical_revision="0.0.0-53cb5f7", destination_canonical_service="srv-octohelm", destination_principal="spiffe://cluster.local/ns/octohelm/sa/default", destination_service="srv-octohelm.octohelm.svc.cluster.local", destination_service_name="srv-octohelm", destination_service_namespace="octohelm", destination_version="0.0.0-53cb5f7", destination_workload="srv-octohelm", destination_workload_namespace="octohelm", instance="10.58.5.177:15090", job="envoy-stats", namespace="istio-system", pod_name="istio-ingressgateway-678444ccdd-2rt5c", reporter="source", request_protocol="http", response_code="200", response_flags="-", source_app="istio-ingressgateway", source_canonical_revision="latest", source_canonical_service="istio-ingressgateway", source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account", source_version="unknown", source_workload="istio-ingressgateway", source_workload_namespace="istio-system"}
```

**Comment by morlay** [comment]
metrics collected. but with `{connection_security_policy="unknown"}`, need to find out why

![image](https://user-images.githubusercontent.com/1667873/90715402-beccd980-e2dc-11ea-9570-d5a1f1cf5ec5.png)
by `istioctl dashboard prometheus <pod_name>.<namespace>` 

kiali not handle this.

**Comment by Mengkzhaoyun** [comment]
under version 1.6.8
the same deployment when i use the amd64 version on x86 server.
istio/proxyv2:1.6.8
istio/pilot:1.6.8 
the prometheus search result contains istio_requests_total metrics

when i use the arm64 version on aarch64 server
querycapistio/proxyv2:1.6.8-arm64
querycapistio/pilot:1.6.8-arm64
the prometheus search result without istio_requests_total metrics
![image](https://user-images.githubusercontent.com/6711398/90715966-4ebf5300-e2de-11ea-85d9-4e69b7c28249.png)

eee

I am sorry after 10hours the metrics came out.

**Comment by Mengkzhaoyun** [comment]
3ks for you project .
my booinfo sample had show it route in kiali
![image](https://user-images.githubusercontent.com/6711398/90716159-d4db9980-e2de-11ea-8315-ef515edb77dc.png)

**Comment by morlay** [comment]
but i have issue with `{connection_security_policy="unknown"}` with 1.6.7 🤣 

seems 1.6.8 fixed that? i will upgrade to check.

**Comment by morlay** [comment]
@Mengkzhaoyun

it's my fault.  1.6.8 is rebuilded to docker hub. need to force pull it.

`ISTIO_META_ISTIO_VERSION` & `ISTIO_META_ISTIO_PROXY_SHA` is important in docker.

this why `istio_*` metrics not exists

![image](https://user-images.githubusercontent.com/1667873/90741983-e8e4c280-e301-11ea-93cc-9809095e9589.png)
