### ISSUE TITLE
Do we have a docker image versiond 1.9.6 and architecture is arm64

### ISSUE THREAD

**Issue by dsy3502** [querycap/istio#63]
Do we have a docker image versiond 1.9.6 and architecture is arm64

**Comment by morlay** [comment]
triggered https://github.com/querycap/istio/actions/runs/1011065911

envoy need to compiling more that 1h30min.

I haven't use 1.9.x any more. 

if next fixed version you need, please PR to `release-1.9` to upgrade here only 
https://github.com/querycap/istio/blob/release-1.9/build/istio/Dockerfile.version#L1

**Comment by morlay** [comment]
pushed
