### ISSUE TITLE
libwee8.a does not exist 

### ISSUE THREAD

**Issue by maikoulin** [querycap/istio#81]
# Move compiled library to the expected destinations.
popd
mv $ROOT/wee8/out/wee8/obj/libwee8.a bazel-out/aarch64-opt/bin/external/com_googlesource_chromium_v8/libwee8.a
')
ERROR: /tmp/bazel/_bazel_root/858f7022510154a9c012e8908a11b859/external/com_googlesource_chromium_v8/BUILD.bazel:33:8: Executing genrule @com_googlesource_chromium_v8//:build failed: (Exit 1): process-wrapper failed: error executing command 

![image](https://user-images.githubusercontent.com/9984908/142589358-9fda9a87-7be8-455c-800d-4973fc994b95.png)

![image](https://user-images.githubusercontent.com/9984908/142589451-1e035cbf-4eca-4d59-be68-6e8edbe74a36.png)

**Comment by maikoulin** [comment]
make build.envoy

**Comment by maikoulin** [comment]
➜  bazel git:(ed148b6) uname -a
Linux node2 4.18.0-147.8.1.el7.aarch64 #1 SMP Wed Apr 15 18:13:44 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by morlay** [comment]
If you couldn't reproduce the system env follow https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile,
please build in docker

**Comment by maikoulin** [comment]
build-tools has been built .
