### ISSUE TITLE
istio operator init verify crd creation failed

### ISSUE THREAD

**Issue by zhangkepi** [querycap/istio#84]
when i install occurs errors, details as follow

$ istioctl operator init --hub=docker.io/querycapistio --tag=1.12.2
Using operator Deployment image: docker.io/querycapistio/operator:1.12.2
- Processing resources for Istio operator.                                                                                                                      2022-01-23T16:22:07.488286Z	error	installer	failed to verify CRD creation; the server could not find the requested resource
Istio operator encountered an error: failed to wait for resource: failed to verify CRD creation: the server could not find the requested resource             
failed to wait for resource: failed to verify CRD creation: the server could not find the requested resource

**Comment by morlay** [comment]
This repo is a distro for arm64, so pls only open issues about arm64.  

Other issues should found in  https://github.com/istio/istio/issues/36944

**Comment by zhangkepi** [comment]
> This repo is a distro for arm64, so pls only open issues about arm64.
> 
> Other issues should found in [istio/istio#36944](https://github.com/istio/istio/issues/36944)

I'm installed on ubuntu20.04 arm64 occurs about error
