### ISSUE TITLE
你好，我想问一下在x86下编译arm的可行性

### ISSUE THREAD

**Issue by a2659802** [querycap/istio#98]
官方现在对arm架构的支持是什么情况，搜了一会代码发现有几行注释
```bash
# * docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
# * docker buildx create --name multi-arch --platform linux/amd64,linux/arm64 --use
# * export DOCKER_ARCHITECTURES="linux/amd64,linux/arm64"
```
似乎是用qemu模拟arm架构，不过看了一眼文件名似乎是base镜像。
我主要想问两个问题：
1. 官方的编译脚本是否支持在x86环境下编译管理面和数据面的镜像？
2. 能否提供一下ARM环境下编译的步骤，需要设置哪些环境变量？

（抱歉，我英文比较差，看到作者地区写的China，不得已使用中文提问
（注：我目标版本是1.11.3

**Comment by morlay** [comment]
golang 本身支持交叉编译，可以直接构建。
但 istio 依赖 envoy，构建环境过于复杂，只能在原生环境做，qemu 非常慢。

我提过几个 pr，代码库本身已经支持多架构构建，现在是卡在 istio 的 ci 环境。
详见这个仓库的 Makefile，步骤 readme 的图已经很清楚了。

官方支持应该会走这张图的步骤
https://github.com/istio/test-infra/issues/3413#issuecomment-1048378743

**Comment by a2659802** [comment]
好吧，果然还是envoy的问题。还好还有现成的用，多谢大佬
